#' @export
implement_breakthrough_reduced_transmissibility <- function(n_offspring,                   # number of offspring associated with the index infection
                                                            offspring_infection_times,     # timings (relative to index infection time) of infections of secondary offspring
                                                            vaccine_efficacy_transmission, # vaccines effect on transmissibility in breakthrough infections
                                                            offspring_function_draw) {     # characteristics of the secondary offspring generated by the index infection

  ## Subsetting index_offspring_function_draw to get the infections that don't occur because of the reduced transmissibility of breakthrough infections
  offspring_vaccine_retained <- rbinom(n = n_offspring, size = 1, prob = 1 - vaccine_efficacy_transmission)
  offspring_vaccine_retained_index <- which(offspring_vaccine_retained == 1)
  offspring_vaccine_averted_index <- which(offspring_vaccine_retained == 0)

  ## Modifying the offspring function draw to remove the infections averted by the reduced transmissibility of vaccinated individuals
  offspring_function_draw$offspring_characteristics <- offspring_function_draw$offspring_characteristics[offspring_vaccine_retained_index, ]  # subsetting the offspring dataframe to only retain the infections that weren't averted
  offspring_function_draw$total_offspring <- length(offspring_vaccine_retained_index)                                                         # updating total number of offspring to reflect loss of averted infections

  ## If any of the averted infections are household infections, we ALSO need to update the information in offspring_function_draw of any infections who share that household (i.e. who aren't averted, but share a household with an averted infection)
  ## - Specifically, we need to update the cumulative household infections tracker and the vector that tracks which household members have been infected,
  ##   and remove the quarantine averted infections from both of these
  ## - Note that because of the way the offspring function is set up, the "household" infections must all belong to the same household,
  ##   which is the same household as the index infection
  offspring_vaccine_averted_transmission_route <- offspring_function_draw$offspring_characteristics$transmission_route[offspring_vaccine_averted_index] # getting the transmisssion route of each of the averted infections
  offspring_vaccine_averted_hh_member_index <- offspring_function_draw$offspring_characteristics$hh_member_index[offspring_vaccine_averted_index]       # getting the hh member ids of each of the averted infections
  if ("household" %in% index_offspring_vaccine_averted_transmission_route) { # are any of the averted infections ones who got infected in a household?

    ## Removing the averted household infections from the cumulative total household infections tracker for other household members
    offspring_num_household_infections_averted <- sum(offspring_vaccine_averted_transmission_route == "household")
    offspring_function_draw$new_hh_cumulative_infections <- offspring_function_draw$new_hh_cumulative_infections - offspring_num_household_infections_averted
    offspring_function_draw$offspring_characteristics$hh_infections[offspring_function_draw$offspring_characteristics$transmission_route == "household"] <- offspring_function_draw$new_hh_cumulative_infections

    ## Modifying the list of all ids of infected household members to account for the averted infections (i.e. remove the averted infections from that list)
    offspring_vaccine_averted_household_member_id <- offspring_vaccine_averted_hh_member_index[which(offspring_vaccine_averted_transmission_route == "household")]
    offspring_vaccine_averted_household_member_index_for_removal <- which(unlist(offspring_function_draw$new_hh_infected_index) %in% offspring_vaccine_averted_household_member_id)
    offspring_function_draw$new_hh_infected_index <- list(unlist(offspring_function_draw$new_hh_infected_index)[-offspring_vaccine_averted_household_member_index_for_removal])
    offspring_function_draw$offspring_characteristics$hh_infected_index[offspring_function_draw$offspring_characteristics$transmission_route == "household"] <- I(offspring_function_draw$new_hh_infected_index)

  }

  # Updating index_n_offspring and secondary_infection_times in light of new removals due to reduced transmissibility of breakthrough infections
  n_offspring <- sum(offspring_vaccine_retained)                                                    # accounting for infections averted by reduced transmissibility of breakthrough vaccinated infections
  infection_times <- offspring_infection_times[offspring_vaccine_retained_index]                    # removing infections averted by reduced transmissibility of breakthrough vaccinated infections

  return(list(updated_n_offspring = n_offspring,
              updated_infection_times = infection_times,
              updated_offspring_function_draw = offspring_function_draw))

}
