#' @export
implement_ring_vaccination <- function(n_offspring,                            # number of offspring associated with the index infection
                                       offspring_infection_times,              # timings (relative to index infection time) of infections of secondary offspring
                                       vaccine_efficacy_infection,             # vaccine efficacy against infection
                                       time_to_contact_vaccination,            # time between infection of index and vaccination of their contacts
                                       time_to_contact_vaccination_protection, # time between infection of index and vaccination protection developing in contacts
                                       offspring_function_draw) {              # characteristics of the secondary offspring generated by the index infection

  ## Creating vectors to store whether or not secondary infections are successfully ring-vaccinated, protected and/or prevented
  offspring_vaccinated_successfully <- vector(mode = "integer", length = n_offspring)    ## vector of whether secondary infections get vaccinated in time
  offspring_protected_successfully <- vector(mode = "integer", length = n_offspring)     ## vector of whether secondary infections get protected in time
  offspring_infection_retained <- vector(mode = "integer", length = n_offspring)         ## vector of whether secondary infections are retained (i.e. not prevented by ring vaccination)
  offspring_infection_retained[1:length(offspring_infection_retained)] <- 1              ## default to infections being retained; and then flow through below to see if they get removed

  ## Looping over secondary infections and evaluating whether they're vaccinated, protected and/or prevented
  for (i in 1:n_offspring) {

    # If infection would otherwise occur AFTER (potential) ring-vaccination
    if (time_to_contact_vaccination <= offspring_infection_times[i]) {
      offspring_vaccinated_successfully[i] <- rbinom(n = 1, size = 1, prob = vaccine_coverage)  # are they vaccinated?
      offspring_protected_successfully[i] <- ifelse(offspring_vaccinated_successfully[i] == 1 & time_to_contact_vaccination_protection <= offspring_infection_times[i], 1, 0) # does protection develop in time?
      offspring_successful_protection <- rbinom(n = 1, size = 1, prob = vaccine_efficacy_infection * offspring_protected_successfully[i])   # does protection successfully stop infection?
      offspring_retained[i] <- ifelse(offspring_successful_protection == 1, 0, 1)               # is the infection retained (i.e. ring-vaccination fails to avert)

    # If infection would otherwise occur BEFORE ring-vaccination
    } else {
      offspring_vaccinated_successfully[i] <- 0 ## note that we're eliding together "unvaccinated" and "vaccinated after infection occurs" here
      offspring_retained[i] <- 1
    }
  }
  offspring_ring_vaccine_retained_index <- which(offspring_retained == 1)  # which secondary infections were NOT averted by ring-vaccination and thus are retained for inclusion in the dataframe
  offspring_ring_vaccine_averted_index <- which(offspring_retained == 0)   # which secondary infections ARE averted by ring vaccination

  ## Updating index_offspring_function_draw to reflect the infections averted because of ring vaccination
  offspring_function_draw$offspring_characteristics <- offspring_function_draw$offspring_characteristics[offspring_ring_vaccine_retained_index, ]        # subsetting the offspring dataframe to only retain the infections that weren't averted
  offspring_function_draw$total_offspring <- length(offspring_ring_vaccine_retained_index)                                                               # updating total number of offspring to reflect loss of averted infections

  ## If any of the averted infections are household infections, we ALSO need to update the information in offspring_function_draw of any infections who share that household (i.e. who aren't averted, but share a household with an averted infection)
  ## - Specifically, we need to update the cumulative household infections tracker and the vector that tracks which household members have been infected,
  ##   and remove the quarantine averted infections from both of these
  ## - Note that because of the way the offspring function is set up, the "household" infections must all belong to the same household,
  ##   which is the same household as the index infection
  offspring_ring_vaccine_averted_transmission_route <- offspring_function_draw$offspring_characteristics$transmission_route[offspring_ring_vaccine_averted_index]  # getting the transmisssion route of each of the averted infections
  offspring_ring_vaccine_averted_hh_member_index <- offspring_function_draw$offspring_characteristics$hh_member_index[offspring_ring_vaccine_averted_index]        # getting the hh member ids of each of the averted infections
  if ("household" %in% offspring_ring_vaccine_averted_transmission_route) {

    ## Removing the averted household infections from the cumulative total
    offspring_num_household_infections_averted <- sum(offspring_ring_vaccine_averted_transmission_route == "household")
    offspring_function_draw$new_hh_cumulative_infections <- offspring_function_draw$new_hh_cumulative_infections - offspring_num_household_infections_averted
    offspring_function_draw$offspring_characteristics$hh_infections[offspring_function_draw$offspring_characteristics$transmission_route == "household"] <- offspring_function_draw$new_hh_cumulative_infections

    ## Modifying the list of all ids of infected household members to account for the averted infections
    offspring_ring_vaccine_averted_household_member_id <- offspring_ring_vaccine_averted_hh_member_index[which(offspring_ring_vaccine_averted_transmission_route == "household")]
    offspring_ring_vaccine_averted_household_member_index_for_removal <- which(unlist(offspring_function_draw$new_hh_infected_index) %in% offspring_ring_vaccine_averted_household_member_id)
    offspring_function_draw$new_hh_infected_index <- list(unlist(offspring_function_draw$new_hh_infected_index)[-offspring_ring_vaccine_averted_household_member_index_for_removal])
    offspring_function_draw$offspring_characteristics$hh_infected_index[offspring_function_draw$offspring_characteristics$transmission_route == "household"] <- I(offspring_function_draw$new_hh_infected_index)

  }

  # Updating index_n_offspring and secondary_infection_times in light of new removals due to quarantining
  n_offspring <- sum(offspring_retained)                                                  # accounting for infections averted by ring vaccination
  infection_times <- offspring_infection_times[offspring_ring_vaccine_retained_index]     # removing infections averted by by ring vaccination

  ## Generating information on timing of ring-vaccination, protection etc for the retained infections
  offspring_vaccinated <- ifelse(offspring_vaccinated_successfully[offspring_ring_vaccine_retained_index] == 0, 0, 1)                                           # of the retained infections, which are vaccinated
  offspring_time_vaccinated <- ifelse(offspring_vaccinated_successfully[offspring_ring_vaccine_retained_index] == 1, time_to_contact_vaccination, NA)           # of the retained infections, when are they vaccinated (relative to infection time of index)
  offspring_vaccinated_before_infection <- ifelse(offspring_vaccinated_successfully[offspring_ring_vaccine_retained_index] == 0, NA, 1)                         # (currently we combine all individuals not vaccinated and vaccinated after infection into "unvaccinated", so all vaccinated individuals necessarily got vaccinated before infection)
  offspring_time_protected <- ifelse(offspring_vaccinated_successfully[offspring_ring_vaccine_retained_index] == 1, time_to_contact_vaccination_protection, NA) # of the retained infections, when are they protected (relative to infection time of index)
  offspring_protected_before_infection <- ifelse(is.na(offspring_time_protected), NA, ifelse(offspring_time_protected <= offspring_pruned_infection_times, 1, 0))  # retained infections were protected by vaccine before infection (i.e. vaccine protection successfully developed but failed to protect)
  offspring_protected_after_infection <- ifelse(is.na(offspring_time_protected), NA, ifelse(offspring_time_protected > offspring_pruned_infection_times, 1, 0))    # retained infections were NOT protected by vaccine before infection (i.e. vaccine protection did not develop in time to protect)

  return(list(updated_n_offspring = n_offspring,
              updated_infection_times = infection_times,
              updated_offspring_function_draw = offspring_function_draw,
              vaccination_info = list(offspring_vaccinated,
                                      offspring_time_vaccinated,
                                      offspring_vaccinated_before_infection,
                                      offspring_time_protected,
                                      offspring_protected_before_infection,
                                      offspring_protected_after_infection)))

}

