#' @export
implement_quarantine <- function(symptom_onset_time,            # time after infection that the index infection develops symptoms
                                 quarantine_time,               # time after symptom onset that the index infection quarantines
                                 n_offspring,                   # number of offspring associated with the index infection
                                 offspring_infection_times,     # timings (relative to index infection time) of infections of secondary offspring
                                 offspring_function_draw,       # characteristics of the secondary offspring generated by the index infection
                                 quarantine_efficacy_household, # efficacy of quarantining at preventing household infections
                                 quarantine_efficacy_else) {    # efficacy of quarantining at preventing infections from other sources

  ## Check offspring infection times relative to time of quarantining (i.e. do they otherwise occur before or after quarantining)
  ##  1 = quarantine can avert this infection, 0 is the infection occurs before quarantining
  quarantine_possible_avert <- ifelse((symptom_onset_time + quarantine_time) < offspring_infection_times, 1, 0)  # Only if an infection occurs later than quarantining can it be averted by quarantine

  ## Establish different levels of efficacy of quarantining at preventing transmission for household vs other transmission routes
  quarantine_efficacy <- ifelse(offspring_function_draw$offspring_characteristics$transmission_route == "household",   # depending on where transmission occurs, use different quarantining efficacy
                                quarantine_efficacy_household, quarantine_efficacy_else)

  ## Implementing quarantining and identifying the infections NOT prevented by quarantining (i.e. those to retain = 1, those averted = 0)
  offspring_quarantine_retained <- rbinom(n = n_offspring, size = 1, prob = 1 - (quarantine_possible_avert * quarantine_efficacy))
  offspring_quarantine_retained_index <- which(offspring_quarantine_retained == 1)
  offspring_quarantine_averted_index <- which(offspring_quarantine_retained == 0)

  ## Modifying the offspring function draw to remove the infections averted by quarantining
  offspring_function_draw$offspring_characteristics <- offspring_function_draw$offspring_characteristics[offspring_quarantine_retained_index, ]  # subsetting the offspring dataframe to only retain the infections that weren't averted
  offspring_function_draw$total_offspring <- length(offspring_quarantine_retained_index)                                                         # updating total number of offspring to reflect loss of averted infections

  ## If any of the averted infections are household infections, we ALSO need to update the information in offspring_function_draw of any infections who share that household (i.e. who aren't averted, but share a household with an averted infection)
  ## - Specifically, we need to update the cumulative household infections tracker and the vector that tracks which household members have been infected,
  ##   and remove the quarantine averted infections from both of these
  ## - Note that because of the way the offspring function is set up, the "household" infections must all belong to the same household,
  ##   which is the same household as the index infection
  offspring_quarantine_averted_transmission_route <- offspring_function_draw$offspring_characteristics$transmission_route[offspring_quarantine_averted_index] # getting the transmisssion route of each of the averted infections
  offspring_quarantine_averted_hh_member_index <- offspring_function_draw$offspring_characteristics$hh_member_index[offspring_quarantine_averted_index]       # getting the hh member ids of each of the averted infections

  if ("household" %in% offspring_quarantine_averted_transmission_route) {

    ## Removing the averted household infections from the cumulative total
    offspring_num_household_infections_averted <- sum(offspring_quarantine_averted_transmission_route == "household")
    offspring_function_draw$new_hh_cumulative_infections <- offspring_function_draw$new_hh_cumulative_infections - offspring_num_household_infections_averted
    offspring_function_draw$offspring_characteristics$hh_infections[offspring_function_draw$offspring_characteristics$transmission_route == "household"] <- offspring_function_draw$new_hh_cumulative_infections

    ## Modifying the list of all ids of infected household members to account for the averted infections
    offspring_quarantine_averted_household_member_id <- offspring_quarantine_averted_hh_member_index[which(offspring_quarantine_averted_transmission_route == "household")]
    offspring_quarantine_averted_household_member_index_for_removal <- which(unlist(offspring_function_draw$new_hh_infected_index) %in% offspring_quarantine_averted_household_member_id)
    offspring_function_draw$new_hh_infected_index <- list(unlist(offspring_function_draw$new_hh_infected_index)[-offspring_quarantine_averted_household_member_index_for_removal])
    offspring_function_draw$offspring_characteristics$hh_infected_index[offspring_function_draw$offspring_characteristics$transmission_route == "household"] <- I(offspring_function_draw$new_hh_infected_index)

  }

  # Updating index_n_offspring and secondary_infection_times in light of new removals due to quarantining
  n_offspring <- sum(offspring_quarantine_retained)                                                       # accounting for infections averted by quarantine from index_n_offspring
  infection_times <- infection_times[offspring_quarantine_retained_index]                                 # removing infections averted by quarantine from secondary_infection_times

  ## Returning the number of offspring, offspring infection times and characteristics after removing infections averted by quarantining
  return(list(updated_n_offspring = n_offspring,
              updated_infection_times = infection_times,
              updated_offspring_function_draw = offspring_function_draw))

}

